http:
  routers:
    submission:
      rule: PathPrefix(`/api`)
      entryPoints:
        - web
      middlewares:
        - submission-auth
        - submission-strip
        - submission-rl
      service: submission

    front:
      rule: PathPrefix(`/`)
      entryPoints:
        - web
      priority: 1
      service: front

  middlewares:
    submission-auth:
      basicAuth:
        users:
          - "apiuser:$2y$05$y8t1dZiK1lI5zgYC/i4Q0.DlKVkdM62dIXWJtdGb4ro6VqQT2tUK6"
    submission-strip:
      stripPrefix:
        prefixes:
          - /api
        forceSlash: false
    submission-rl:
      rateLimit:
        average: 5
        burst: 10

  services:
    submission:
      loadBalancer:
        servers:
          - url: http://cstr_submission_api:8080
    front:
      loadBalancer:
        servers:
          - url: http://cstr_frontend:80
